### ISSUE TITLE
Cannot blacklist the subject "Studiecafé"

### ISSUE THREAD

**Issue by mads256h** [Benjadahl/UDPlus-Plus#34]
Maybe because of the the letter "é"

**Comment by RasmusRendal** [comment]
Nope, it's because someone in [commit 6e01c84](https://github.com/Benjadahl/UDPlus-Plus/commit/6e01c84dbd4849cbd9027013f5531f8a03a14e54) removed the feature completely. Not to worry though, I fixed it in [commit 0a701cc](https://github.com/Benjadahl/UDPlus-Plus/commit/0a701ccc730fd96346dd4f244da81923cc6d9832), and it should be there in the next update.
