### ISSUE TITLE
Ability to change color of the text on lesson cards

### ISSUE THREAD

**Issue by viktorstrate** [Benjadahl/UDPlus-Plus#65]
It is currently very hard to read the text of lessons, if you change the theme to "Black".

I can't find any settings for changing the text for lesson cards.

![screenshot from 2017-08-14 16-35-00](https://user-images.githubusercontent.com/4233458/29276338-8ecfaf24-810e-11e7-8c6b-024ac2d5b5ed.png)

**Comment by jbjjbjjbj** [comment]
Hey @viktorstrate. I just looked at your issue, and added your request to our "system" :-D. 
It wil however take some time before this change reaches the chrome store, because we have a pretty slow release schedule.
If you want to test it yourself, you can just manually install it, FROM THE DEV BRANCH. [GUIDE](https://github.com/Benjadahl/UDPlus-Plus/wiki/Install-Guide(From-Source))

The change was added in commit 7bbd551 and cbdc271.
