### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by viktorstrate** [Benjadahl/UDPlus-Plus#75]
It would be great if the extension supported firefox and other browsers.

**Comment by jbjjbjjbj** [comment]
Yeah this was something we discussed a lot, and something that was relative good support for in the beginning. The problem is that we use features like the auto filesaver uses the chrome filesystem storage and in a bit hacky way. It's probably possible but none has the time to try. 

If you want a stripped down version without the dashboard and file caching, I will try that. 

Otherwise you are more than welcome to make the filesaver etc. work in firefox. Sorry for the late response :-D

**Comment by RasmusRendal** [comment]
Mate, we're volunteers. We respond as late as we want. What's going to happen, we get fired?

**Comment by viktorstrate** [comment]
Thank you for the response, @jbjjbjjbj :)
I might try to make it compatiable with Firefox, if I find the time.

**Comment by agraven** [comment]
Do take note that with the upcoming stable release of Firefox 57, the plugin architecture will be different from the one of prior versions. This is to our advantage though, as the new WebExtentions one resembles Chrome's extention model much more closely, if I remember correctly.

**Comment by RasmusRendal** [comment]
Chrome uses WebExtensions. Firefox has used WebExtensions for a while, all Firefox 57 is doing is finally getting rid of support for their old extension API. UD++ worked in Firefox for a while, but because Firefox and Chrome support different browser APIs, we have only figured out how to store files in Chrome. [Although this new thing might be something.](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Working_with_files)

So we just kinda dropped support for Firefox rather than write seperate versions, because we're lazy. But if you'd like to set up support for it, that'd actually be rather great, because I've been using Firefox primarily recently and I'm kinda missing this extension.

**Comment by jbjjbjjbj** [comment]
Just uploaded the extension to the web extension website. It can be found here
https://addons.mozilla.org/en-US/firefox/addon/udplus-plus/
